### ISSUE TITLE
The required additional checkpoints for running inference

### ISSUE THREAD

**Issue by shivangi-aneja** [ronslos/Unsupervised-High-Fidelity-Facial-Texture-Generation-and-Reconstruction#2]
Hi,

Would it be possible to also get access to the additional checkpoints you used in your pipeline? 
More specifically the checkpoints  `epoch_20.pth`,  `params_lsfm_465000.pth`, `rignet_no_trans2_84000.pth` used in file `generate_3d.py`

**Comment by ronslos** [comment]
Hi,
Sorry for the delay,
I have uploaded all files requested to google drive and updated the link in the Readme.
Please let us know if you require anything further.
