### ISSUE TITLE
UV-Map used for mapping textures

### ISSUE THREAD

**Issue by shivangi-aneja** [ronslos/Unsupervised-High-Fidelity-Facial-Texture-Generation-and-Reconstruction#3]
Would it be possible for you to share the UV mapping you used in your experiments? 
Specifically, the files `uv_map_mp_open_mouth.npy` and `uv_map_closed_mouth.npy` from your repo. It would really be useful for rendering the textures

**Comment by ronslos** [comment]
Hi, 
I have uploaded the UV map files to google drive.
